[package]
name = "egui_commonmark"
authors = ["Erlend Walstad"]
version = "0.7.1"
edition = "2021"
description = "Commonmark viewer for egui"
keywords = ["commonmark", "egui"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/lampsitter/egui_commonmark"
documentation = "https://docs.rs/egui_commonmark"
include = ["src/*.rs", "LICENSE-MIT", "LICENSE-APACHE", "Cargo.toml"]

[dependencies]
egui = "0.21"
pulldown-cmark = { version = "0.9.2", default-features = false }
image = { version = "0.24", default-features = false, features = ["png"] }

syntect = { version = "5.0.0", optional = true, default-features = false, features = ["default-fancy"] }

resvg = { version = "0.20.0", optional = true }
usvg = { version = "0.20.0", optional = true }
tiny-skia = { version = "0.6.3", optional = true }

url = { version = "2.2.2", optional = true }
ehttp = { version = "0.2.0", optional = true }

[features]
# Syntax highlighting for code blocks
syntax_highlighting = ["syntect"]
# Support loading svg images
svg = ["resvg", "usvg", "tiny-skia"]

# Fetch images over http
fetch = ["ehttp", "url", "image/jpeg"]

[dev-dependencies]
eframe = "0.21"

[package.metadata.docs.rs]
features = ["syntax_highlighting", "svg"]
